import bcrypt from 'bcryptjs';

export const getSeedData = () => {
  const studentPasswordHash = bcrypt.hashSync('student123', 10);
  const staffPasswordHash = bcrypt.hashSync('staff123', 10);

  const users = [
    {
      id: 'stud_001',
      name: 'Vignesh B',
      email: 'student@college.edu',
      password_hash: studentPasswordHash,
      role: 'student',
      department: 'Computer Science and Engineering',
      phone: '+91 98765 43210',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      register_number: '23CSE001',
      year: '2nd Year',
      semester: '4th Semester',
      section: 'A',
      cgpa: '8.85',
      attendance_percentage: 92.00,
      employee_id: null,
      designation: null,
      cabin: null,
      status: 'active'
    },
    {
      id: 'stud_002',
      name: 'Ananya S',
      email: 'ananya.23it@college.edu',
      password_hash: studentPasswordHash,
      role: 'student',
      department: 'Information Technology',
      phone: '+91 98765 43211',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      register_number: '23IT042',
      year: '2nd Year',
      semester: '4th Semester',
      section: 'B',
      cgpa: '8.92',
      attendance_percentage: 94.50,
      employee_id: null,
      designation: null,
      cabin: null,
      status: 'active'
    },
    {
      id: 'stud_003',
      name: 'Karthik M',
      email: 'karthik.22ece@college.edu',
      password_hash: studentPasswordHash,
      role: 'student',
      department: 'Electronics and Communication',
      phone: '+91 98765 43212',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      register_number: '22ECE015',
      year: '3rd Year',
      semester: '6th Semester',
      section: 'A',
      cgpa: '8.40',
      attendance_percentage: 89.00,
      employee_id: null,
      designation: null,
      cabin: null,
      status: 'active'
    },
    {
      id: 'stud_004',
      name: 'Priya R',
      email: 'priya.23ai@college.edu',
      password_hash: studentPasswordHash,
      role: 'student',
      department: 'Artificial Intelligence and Data Science',
      phone: '+91 98765 43213',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
      register_number: '23AIDS019',
      year: '2nd Year',
      semester: '4th Semester',
      section: 'A',
      cgpa: '9.10',
      attendance_percentage: 96.00,
      employee_id: null,
      designation: null,
      cabin: null,
      status: 'active'
    },
    {
      id: 'stud_005',
      name: 'Sanjay K',
      email: 'sanjay.22mech@college.edu',
      password_hash: studentPasswordHash,
      role: 'student',
      department: 'Mechanical Engineering',
      phone: '+91 98765 43214',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      register_number: '22MECH008',
      year: '3rd Year',
      semester: '6th Semester',
      section: 'B',
      cgpa: '8.15',
      attendance_percentage: 87.50,
      employee_id: null,
      designation: null,
      cabin: null,
      status: 'active'
    },
    {
      id: 'stud_006',
      name: 'Divya P',
      email: 'divya.23cse@college.edu',
      password_hash: studentPasswordHash,
      role: 'student',
      department: 'Computer Science and Engineering',
      phone: '+91 98765 43215',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      register_number: '23CSE055',
      year: '2nd Year',
      semester: '4th Semester',
      section: 'B',
      cgpa: '8.60',
      attendance_percentage: 91.00,
      employee_id: null,
      designation: null,
      cabin: null,
      status: 'active'
    },
    {
      id: 'stud_007',
      name: 'Rahul G',
      email: 'rahul.22eee@college.edu',
      password_hash: studentPasswordHash,
      role: 'student',
      department: 'Electrical and Electronics',
      phone: '+91 98765 43216',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      register_number: '22EEE031',
      year: '3rd Year',
      semester: '6th Semester',
      section: 'A',
      cgpa: '8.35',
      attendance_percentage: 88.00,
      employee_id: null,
      designation: null,
      cabin: null,
      status: 'active'
    },
    {
      id: 'stud_008',
      name: 'Sneha K',
      email: 'sneha.23it@college.edu',
      password_hash: studentPasswordHash,
      role: 'student',
      department: 'Information Technology',
      phone: '+91 98765 43217',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      register_number: '23IT088',
      year: '2nd Year',
      semester: '4th Semester',
      section: 'A',
      cgpa: '8.75',
      attendance_percentage: 93.00,
      employee_id: null,
      designation: null,
      cabin: null,
      status: 'active'
    },
    {
      id: 'staff_001',
      name: 'Dr. K. Ramanathan',
      email: 'staff@college.edu',
      password_hash: staffPasswordHash,
      role: 'staff',
      department: 'Computer Science and Engineering',
      phone: '+91 94432 10987',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      register_number: null,
      year: null,
      semester: null,
      section: null,
      cgpa: null,
      attendance_percentage: 0.00,
      employee_id: 'EMP-CSE-104',
      designation: 'Associate Professor & Event Convener',
      cabin: 'CSE Block - Room 304',
      status: 'active'
    },
    {
      id: 'staff_002',
      name: 'Prof. S. Meenakshi',
      email: 'meenakshi.it@college.edu',
      password_hash: staffPasswordHash,
      role: 'staff',
      department: 'Information Technology',
      phone: '+91 94432 10988',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      register_number: null,
      year: null,
      semester: null,
      section: null,
      cgpa: null,
      attendance_percentage: 0.00,
      employee_id: 'EMP-IT-082',
      designation: 'Assistant Professor (Sr. Gr)',
      cabin: 'IT Block - Room 201',
      status: 'active'
    },
    {
      id: 'staff_003',
      name: 'Dr. R. Balaji',
      email: 'balaji.ece@college.edu',
      password_hash: staffPasswordHash,
      role: 'staff',
      department: 'Electronics and Communication',
      phone: '+91 94432 10989',
      college: 'Paavai Engineering College',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
      register_number: null,
      year: null,
      semester: null,
      section: null,
      cgpa: null,
      attendance_percentage: 0.00,
      employee_id: 'EMP-ECE-045',
      designation: 'Professor & HOD',
      cabin: 'ECE Block - Room 102',
      status: 'active'
    }
  ];

  return { users };
};
